# Stage 1: Build stage
FROM python:3.10-slim AS builder

# Environment variables
ENV PYTHONDONTWRITEBYTECODE 1  # Prevent Python from writing .pyc files
ENV PYTHONUNBUFFERED 1         # Ensure stdout/stderr are flushed

WORKDIR /app

# Install system dependencies and Python build tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev curl && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project
COPY . /app/

# Collect static files
RUN python manage.py collectstatic --noinput

# Stage 2: Production stage
FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# Copy the build from the first stage
COPY --from=builder /app /app

# Mount the media volume
VOLUME /app/media

# Expose port 8000 for the application
EXPOSE 8000


# Command to run the app with Waitress
CMD ["python", "run_waitress.py"]