app = "samakisamaki"
primary_region = "jnb"

[build]
  dockerfile = "./Dockerfile"

[env]
  DEBUG = "false"
  DJANGO_DEVELOPMENT = "false"
  PROD_DATABASE_URL = "postgres://postgres:${POSTGRES_PASSWORD}@wispy-snowflake-7733.flycast:5432/postgres" # Corrected Port
  PROD_DB_SSL = "false" # Set this to "true" if SSL is required by Fly.io

  ALLOWED_HOSTS = "samakisamaki.fly.dev"
  CSRF_TRUSTED_ORIGINS = "https://samakisamaki.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 30

[[mounts]]
  source = "media_data"
  destination = "/app/media"