# fly.toml app configuration file for samakisamaki

app = "samakisamaki"
primary_region = "jnb"

[build]
  dockerfile = "./Dockerfile"  # Use Dockerfile instead of a prebuilt image

[env]
  DEBUG = "false"
  SECRET_KEY = "your-secret-key"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1  # Ensure at least one machine is always running

[[services]]
  protocol = "tcp"
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[mounts]]
  source = "media_data"  # Name of the Fly volume created
  destination = "/app/media"  # Where media files will be stored
