# Generated by Django 5.0.3 on 2025-01-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="available",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="gluten_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="vegetarian",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("starters", "Starters"),
                    ("main_courses", "Main Courses"),
                    ("desserts", "Desserts"),
                    ("beverages", "Beverages"),
                    ("seafood", "Seafood"),
                    ("specials", "Specials"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(upload_to="menu_items/"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
